services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - /media/default/Extreme\ SSD/postgis_data:/var/lib/postgresql/data

